[package]
name = "codeup-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.9"
hyper = "0.14.20"
serde_derive = "1.0.138"
serde = "1.0.138"
